### ISSUE TITLE
Docsの整備

### ISSUE THREAD

**Issue by ghost** [syuumu200/social-booster#13]
ドキュメンテーションがほとんど整備されていないため、開発者が理解するために、一度全体を理解する必要があり

面倒くさくなると思われる。また、テスト製作をするときのプランを立てるのにも必要なので、重要だと考える。

**Comment by syuumu200** [comment]
理想的なドキュメントをいくつか紹介して頂けませんか？

**Comment by ghost** [comment]
参考例ですが...
[具体的なqiitaの記事](https://qiita.com/koeri3/items/f85a617dcb6efebb2cab)

後、コードカバレッジ率などの話は自分のリポジトリにあるので紹介しておきますね
[Asciidoc-icon-snippets](https://github.com/Stroheim001/asciidoc_icon_snippets)

少なくともReadmeに最低限書かなければいけない内容を提示しました。

ただ、docsに関してはどうしたら良いかは、ヴェロシティとの兼ね合いになるので、それは要相談だと思います。

仕様変更していくうちにdocsとは必ず乖離が生じるからです。

故に大企業の作るプログラムの仕上がりが遅いのはこの部分にあります。もちろん功罪あるとは思います。結局PMが何を考えているか次第だと思います。

**Comment by syuumu200** [comment]
ありがとうごだいます。参考に致します。
